Update devcontainer

diff --git a/.devcontainer/common/rootfs_supervisor/etc/supervisor_scripts/common b/.devcontainer/common/rootfs_supervisor/etc/supervisor_scripts/common
--- a/.devcontainer/common/rootfs_supervisor/etc/supervisor_scripts/common
+++ b/.devcontainer/common/rootfs_supervisor/etc/supervisor_scripts/common
@@ -1,31 +1,38 @@
 #!/bin/bash
-set -eE
 
-SUPERVISOR_VERSON="$(curl -s https://version.home-assistant.io/dev.json | jq -e -r '.supervisor' )"
-DOCKER_TIMEOUT=30
+set -e
+
+export SUPERVISOR_VERSION="$(curl -s https://version.home-assistant.io/dev.json | jq -e -r '.supervisor')"
+HA_ARCH=$(get_arch ha)
+QEMU_ARCH=$(get_arch qemu)
+DOCKER_TIMEOUT=300
 DOCKER_PID=0
+
 
 function start_docker() {
     local starttime
     local endtime
 
-    if grep -q 'Alpine' /proc/version; then
-        # The docker daemon does not start when running Alpine backed WSL2 without adjusting iptables
+    if grep -q 'microsoft-standard\|standard-WSL' /proc/version; then
+        # The docker daemon does not start when running WSL2 without adjusting iptables
         update-alternatives --set iptables /usr/sbin/iptables-legacy || echo "Fails adjust iptables"
+        update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || echo "Fails adjust ip6tables"
     fi
 
     echo "Starting docker."
-    dockerd 2> /dev/null &
+    if stat -f -c %T /var/lib/docker | grep -q overlayfs; then
+        echo "Using \"vfs\" storage driver. Bind mount /var/lib/docker to use the faster overlay2 driver."
+        dockerd --storage-driver=vfs 2> /dev/null &
+    else
+        dockerd --storage-driver=overlay2 2> /dev/null &
+    fi
     DOCKER_PID=$!
-
-    ## Reset iptables (https://github.com/moby/moby/issues/16816#issuecomment-179717327)
-    service docker restart
 
     echo "Waiting for docker to initialize..."
     starttime="$(date +%s)"
     endtime="$(date +%s)"
     until docker info >/dev/null 2>&1; do
-        if [ $((endtime - starttime)) -le $DOCKER_TIMEOUT ]; then
+        if [[ $((endtime - starttime)) -le $DOCKER_TIMEOUT ]]; then
             sleep 1
             endtime=$(date +%s)
         else
@@ -48,7 +55,7 @@ function stop_docker() {
         # Now wait for it to die
         kill "$DOCKER_PID"
         while kill -0 "$DOCKER_PID" 2> /dev/null; do
-            if [ $((endtime - starttime)) -le $DOCKER_TIMEOUT ]; then
+            if [[ $((endtime - starttime)) -le $DOCKER_TIMEOUT ]]; then
                 sleep 1
                 endtime=$(date +%s)
             else
@@ -61,42 +68,56 @@ function stop_docker() {
     fi
 }
 
-
 function cleanup_lastboot() {
-    if [[ -f /tmp/supervisor_data/config.json ]]; then
+    if [[ -f /workspaces/test_supervisor/config.json ]]; then
         echo "Cleaning up last boot"
-        cp /tmp/supervisor_data/config.json /tmp/config.json
-        jq -rM 'del(.last_boot)' /tmp/config.json > /tmp/supervisor_data/config.json
+        cp /workspaces/test_supervisor/config.json /tmp/config.json
+        jq -rM 'del(.last_boot)' /tmp/config.json > /workspaces/test_supervisor/config.json
         rm /tmp/config.json
     fi
 }
 
+function build_supervisor() {
+    docker pull "homeassistant/${HA_ARCH}-builder:dev"
+
+    docker run --rm \
+        --privileged \
+        -v /run/docker.sock:/run/docker.sock \
+        -v "$(pwd):/data" \
+        "homeassistant/${HA_ARCH}-builder:dev" \
+            --generic latest \
+            --target /data \
+            --test \
+            --amd64 \
+            --no-cache
+}
 
 function cleanup_docker() {
     echo "Cleaning up stopped containers..."
-    docker rm "$(docker ps -a -q)" || true
+    docker rm $(docker ps -a -q) || true
 }
 
 function run_supervisor() {
-
-
     mkdir -p /tmp/supervisor_data
+    mkdir -p /workspaces/test_supervisor
+
+    echo "Start Supervisor"
     docker run --rm --privileged \
         --name hassio_supervisor \
         --privileged \
         --security-opt seccomp=unconfined \
-        --security-opt apparmor:unconfined \
+        --security-opt apparmor=unconfined \
         -v /run/docker.sock:/run/docker.sock:rw \
         -v /run/dbus:/run/dbus:ro \
         -v /run/udev:/run/udev:ro \
-        -v /tmp/supervisor_data:/data:rw \
-        -v "$WORKSPACE_DIRECTORY":/data/addons/local:rw \
+        -v "/workspaces/test_supervisor":/data:rw \
         -v /etc/machine-id:/etc/machine-id:ro \
-        -e SUPERVISOR_SHARE="/tmp/supervisor_data" \
-        -e SUPERVISOR_NAME=hassio_supervisor \
+        -v /workspaces/supervisor:/usr/src/supervisor \
+        -e SUPERVISOR_SHARE="/workspaces/test_supervisor" \
+        -e SUPERVISOR_NAME="hassio_supervisor" \
         -e SUPERVISOR_DEV=1 \
-        -e SUPERVISOR_MACHINE="qemux86-64" \
-        "homeassistant/amd64-hassio-supervisor:${SUPERVISOR_VERSON}"
+        -e SUPERVISOR_MACHINE="qemu${QEMU_ARCH}" \
+        "homeassistant/${HA_ARCH}-hassio-supervisor:latest"
 }
 
 function init_dbus() {
@@ -117,6 +138,7 @@ function init_dbus() {
     dbus-daemon --system --print-address
 }
 
+
 function init_udev() {
     if pgrep systemd-udevd; then
         echo "udev is running"
@@ -134,16 +156,13 @@ function init_udev() {
     udevadm trigger && udevadm settle
 }
 
-echo "Start Test-Env"
 
-start_docker
-trap "stop_docker" ERR
+function init_os_agent() {
+    if pgrep os-agent; then
+        echo "os-agent is running"
+        return 0
+    fi
 
-docker system prune -f
+    os-agent &
+}
 
-cleanup_lastboot
-cleanup_docker
-init_dbus
-init_udev
-run_supervisor
-stop_docker
